### PR TITLE
Updated Fipsum extension so hidden elements are ignored

### PR DESCRIPTION
**Pull request by hellopablo**
Updated Fipsum extension so that hidden elements (either by CSS or as the `type` attribute) don't get filled.

In addition:
- Tidied up some markup layout/keeping JSHint happy
- Using handy lib by Jason Farrell to detect if element is hidden by parent stylings
- Added a "test" page to quickly test elements
- `datetime` is deprecated, so using `datetime-local`
- Changed format of getRandomTime() to be 24 hour / zeropadded hours
- Format for `datetime-local` is YYYY-MM-DDTHH:MM:SS, updated to suit

### CODE REVIEW

**Comment by connor** [comment]
:heart_eyes:

**Comment by connor** [comment]
Thank you!

**Comment by hellopablo** [comment]
You're welcome! Do you need to push any buttons to get this pushed into the Chrome store? It's still showing v0.1 for me :(

**Comment by connor** [comment]
Just published an update – should be good now. Thanks again! Apologies about the delay.

**Pull request merged**
